export {default as Home} from "./Home"
export {default as Navbar} from "./Navbar"
export {default as SearchFeed} from "./SearchFeed"
export {default as VideoCard}from "./VideoCard"
export {default as SearchBar} from "./SearchBar"
export {default as Faq} from "./Faq"
export {default as Footer} from "./Footer"
export {default as Movies} from "./Movies"
export {default as TopBar} from "./TopBar"
export {default as Feed} from "./Feed"
export {default as VideoDetail} from "./VideoDetail"